FROM scratch AS ctx
COPY build_files /
COPY system_files/global /system_files/global

FROM docker.io/nvidia/cuda:12.5.1-runtime-ubuntu24.04

RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    --mount=type=tmpfs,dst=/tmp \
    /ctx/ai/build-ai.sh
