FROM scratch AS ctx
COPY build_files /
COPY system_files/global /system_files/global

FROM quay.io/fedora/fedora-bootc:44

RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    /ctx/crmy/build-crmy.sh

RUN bootc container lint
