ARG BASE_IMAGE="${BASE_IMAGE:-ghcr.io/projectbluefin/bluefin-lts-nvidia:testing@sha256:629f6607cd649211f34720551b00cc1fb56909f7f70d49869a3b481e2f23fe0a}"

FROM scratch AS ctx
COPY system_files/edward /ctx/system_files/edward
COPY build_files/edward /ctx/build_scripts
COPY build_files/core /ctx/core
COPY brew /ctx/brew

FROM ${BASE_IMAGE}

ARG BREWFILE_REF="${BREWFILE_REF:-main}"
ARG IMAGE_NAME="${IMAGE_NAME:-blueprint}"
ARG IMAGE_VENDOR="${IMAGE_VENDOR:-huntedraven7}"
ARG SHA_HEAD_SHORT="${SHA_HEAD_SHORT:-deadbeef}"

RUN --mount=type=tmpfs,dst=/tmp \
  --mount=type=cache,dst=/var/cache \
  --mount=type=cache,dst=/var/log \
  --mount=type=bind,from=ctx,source=/ctx,target=/run/context \
  /run/context/build_scripts/build.sh
