FROM scratch AS ctx
COPY build_files /
COPY system_files/global /system_files/global
COPY system_files/aira /system_files/aira

FROM ghcr.io/ublue-os/bazzite-nvidia-open:stable

RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    /ctx/aira/build-aira.sh

RUN bootc container lint
