tap "ublue-os/tap", trusted: true
tap "ublue-os/experimental-tap", trusted: true

cask "devpod-linux"
cask "visual-studio-code-linux"
cask "lm-studio-linux"
cask "zed-linux"
cask "jetbrains-toolbox-linux"

brew "eza"
brew "bun"
brew "starship"
brew "uv"
brew "rustup"
brew "atuin"
brew "bat"
brew "fzf"
brew "gh"
brew "cosign"
brew "stow"
brew "fd"
brew "dysk"
brew "opencode"
brew "npm"

flatpak "io.github.tanaybhomia.Whisp"
flatpak "com.discordapp.Discord"
flatpak "com.heroicgameslauncher.hgl"
flatpak "it.mijorus.gearlever"
flatpak "org.kde.krita"
flatpak "com.ticktick.TickTick"
flatpak "com.jeffser.Alpaca"
flatpak "io.github.alainm23.planify"
flatpak "io.gitlab.news_flash.NewsFlash"
flatpak "moe.launcher.the-honkers-railway-launcher"
flatpak "moe.launcher.sleepy-launcher"
flatpak "moe.launcher.an-anime-game-launcher"
flatpak "io.github.dvlv.boxbuddyrs"
flatpak "net.runelite.RuneLite"
flatpak "io.github.faridjaff.StickyNotesCanvas"
flatpak "org.localsend.localsend_app"
flatpak "net.lutris.Lutris"
flatpak "de.haeckerfelix.Shortwave"
flatpak "dev.geopjr.Calligraphy"
flatpak "org.kde.audiotube"
flatpak "info.febvre.Komikku"
flatpak "us.zoom.Zoom"
flatpak "com.protonvpn.www"
flatpak "com.super_productivity.SuperProductivity"
flatpak "org.gnome.gitlab.ilhooq.Bookup"
flatpak "com.vysp3r.ProtonPlus"
flatpak "md.obsidian.Obsidian"
flatpak "org.inkscape.Inkscape"
flatpak "org.zotero.Zotero"
flatpak "io.github.qwersyk.Newelle"
flatpak "com.google.Chrome"
flatpak "com.valvesoftware.Steam"
